# Generated by Django 5.2.5 on 2025-08-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyprice',
            old_name='currency',
            new_name='currency_code',
        ),
        migrations.RenameField(
            model_name='staffphone',
            old_name='national_code',
            new_name='staff_member',
        ),
        migrations.AlterUniqueTogether(
            name='staffphone',
            unique_together={('staff_member', 'phone_number')},
        ),
    ]
