# Generated by Django 5.2.5 on 2025-08-24 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_rename_currency_currencyprice_currency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('debt_id', models.AutoField(primary_key=True, serialize=False)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_date', models.DateField(auto_now_add=True)),
                ('debt_time', models.TimeField(auto_now_add=True)),
                ('debt_status', models.BooleanField(default=False)),
                ('debt_type', models.CharField(max_length=100)),
                ('debt_description', models.TextField()),
                ('debt_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
